### ISSUE TITLE
[BUG] The directory doesn't contains requirements.txt. Not able to install the dependencies

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [Documentive/TemplateBuddy-Old#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frankhart2018** [comment]
Hey @NirmalKumarJoshi we are in the process of wrapping up the initial build of this thing. Will be adding requirements.txt soon. Thanks for reaching out.

**Comment by NirmalKumarJoshi** [comment]
Sure @frankhart2018 I was willing to contribute in this project. :)

**Comment by frankhart2018** [comment]
Sure would love that. Just give us some time before we wrap up the initial build. We will be open to contributions from first of October.
