### ISSUE TITLE
[FEATURE] Add currently working here (present) option in work experience page

### ISSUE THREAD

**Issue by dhairyaj** [Documentive/TemplateBuddy-Old#17]
**Describe the solution you'd like**
Add a checkbox for the end date and as soon as the checkbox is ticked, the end date option gets disabled.
Previously: (startdate)20/09/2017 - (enddate)some future date
Expected: (startdate)20/09/2017 - (enddate)Present

<strong>Note:</strong> You can start working on the feature only if a maintainer approves the UI (screenshot) in this discussion thread.

**Comment by namantiwari2002** [comment]
Hey , kindly assign this task to me

**Comment by dhairyaj** [comment]
Sure @namantiwari2002 , will assign this to you.

**Comment by namantiwari2002** [comment]
done , check the pull request

**Comment by dhairyaj** [comment]
Merged.

**Comment by frankhart2018** [comment]
Merged.
