### ISSUE TITLE
[FEATURE] UI improvement for templateselect endpoint

### ISSUE THREAD

**Issue by frankhart2018** [Documentive/TemplateBuddy-Old#39]
**Describe the solution you'd like**
The templateselect endpoint (/templateselect) shows only 3 templates per page. In this issue we propose that 3 rows each of 3 resumes be shown in a page (i.e. a total of 9 resumes should be shown in one page).

<strong>Note:</strong> You only start working on the feature if a maintainer approves that request in discussion.

**Comment by headphone-rachit** [comment]
I am interested, if you can provide me this project

**Comment by dhairyaj** [comment]
Sure @headphone-rachit , assigning this to you.

**Comment by tusharnankani** [comment]
I would like to work on this!

**Comment by frankhart2018** [comment]
Sure assigning this to you @tusharnankani.
